"""
Add ~120 tickers covering the user's 88 NSE sub-industries.
"""
import json
from pathlib import Path

PATH = Path("data/tickers.json")

NEW = {
    "JUBLFOOD":   ("Jubilant FoodWorks", "Quick Service Restaurant", 2, 75, "Dominos operator; new store expansion; SSSG + double-digit same-store growth.", "Store growth", "Same-store growth slows", None, []),
    "DEVYANI":    ("Devyani International", "Quick Service Restaurant", 2, 73, "KFC + Pizza Hut operator; store expansion; margin recovery from mix shift.", "Store network expansion", "Store ramp slips", None, []),
    "SAPPHIRE":   ("Sapphire Foods", "Quick Service Restaurant", 2, 70, "KFC + Pizza Hut master franchisee; store growth; margin recovery.", "Network expansion", "Store ramp slips", None, []),
    "WESTLIFE":   ("Westlife Development", "Quick Service Restaurant", 2, 74, "McDonald's India master franchisee; new store openings; SSSG.", "McDonald's franchise", "Same-store weak or competition", None, []),
    "BALRAMCHIN": ("Balrampur Chini Mills", "Sugar", 2, 73, "Sugar + ethanol + power; ethanol blending tailwind; capex done.", "Ethanol blending", "Sugar prices correct", None, []),
    "EIDPARRY":   ("EID Parry (India)", "Sugar", 1, 65, "Sugar + distillery; small-cap, sugar cycle still developing.", "Ethanol ramp", "Sugar cycle weak", None, []),
    "DALMIASUG":  ("Dalmia Bharat Sugar", "Sugar", 2, 70, "Sugar + distillery; capex on ethanol complete; integrated player.", "Ethanol capex complete", "Sugar prices correct", None, []),
    "TRIVENI":    ("Triveni Engineering", "Sugar", 2, 72, "Sugar + engineering; co-generation + distillery; growth steady.", "Distillery + co-gen", "Sugar cycle weak", None, []),
    "TRIDENT":    ("Trident", "Textiles", 2, 74, "Home textile + paper; bedding scale-up; export markets steady.", "Home textile scale-up", "Cotton cost spike or export demand softens", None, []),
    "WELSPUN":    ("Welspun Living", "Textiles", 2, 73, "Home textile + flooring; branded business scaling; export + domestic mix.", "Branded home textile", "Cotton cost spike", None, []),
    "VARDHMAN":   ("Vardhman Textiles", "Textiles", 2, 72, "Yarn + fabric manufacturer; capacity utilisation strong; exports steady.", "Capacity utilisation", "Cotton cost spike", None, []),
    "KPRMILL":    ("KPR Mill", "Textiles", 2, 73, "Apparel + yarn; export focus; scale-up underway.", "Apparel exports", "Cotton cost spike or export slowdown", None, []),
    "INDOCOUNT":  ("Indo Count Industries", "Textiles", 2, 72, "Home textile; export + domestic mix; growth steady.", "Home textile exports", "Cotton cost spike", None, []),
    "SUNTV":      ("Sun TV Network", "Media - Print/Television/Radio", 2, 75, "Tamil + regional TV; subscription + ad revenue steady; cash flow strong.", "Regional TV franchise", "Ad cycle softens or OTT disruption", None, []),
    "ZEEL":       ("Zee Entertainment", "Entertainment", 1, 55, "TV broadcaster + OTT; ad cycle weak; balance sheet stretched.", "OTT + TV distribution", "Ad cycle stays weak", None, ["Ad cycle weakness a watchpoint."]),
    "PVRINOX":    ("PVR INOX", "Entertainment", 2, 72, "Cinema chain; post-merger synergy; ad + F&B margin.", "Post-merger synergy", "Footfalls weak or content line-up weak", None, []),
    "NETWORK18":  ("Network18 Media", "Media - Print/Television/Radio", 1, 62, "TV + digital; ad cycle dependency; small-cap, growth modest.", "TV + digital mix", "Ad cycle weak", None, []),
    "TIPSMUSIC":  ("Tips Industries", "Entertainment", 2, 75, "Music rights + royalties; growth strong; market share.", "Music rights", "Music streaming disruption", None, []),
    "HATHWAY":    ("Hathway Cable & Datacom", "Media - Print/Television/Radio", 1, 55, "Cable + broadband; small-cap, growth modest.", "Cable + broadband", "Cable disruption or competition", None, []),
    "TVTODAY":    ("TV Today Network", "Media - Print/Television/Radio", 1, 60, "English news channel; small-cap, growth modest.", "News channel", "Ad cycle weak", None, []),
    "DISHTV":     ("Dish TV India", "Media - Print/Television/Radio", 1, 50, "DTH operator; small-cap, growth weak, competitive pressure.", "DTH", "DTH competition or churn", None, ["Structural DTH decline."]),
    "JAGRAN":     ("Jagran Prakashan", "Media - Print/Television/Radio", 1, 60, "Print media; circulation; small-cap, growth modest.", "Print media", "Ad cycle weak", None, []),
    "DBCORP":     ("D.B. Corp", "Media - Print/Television/Radio", 1, 55, "Print media; circulation declining; small-cap, growth weak.", "Print media", "Ad cycle weak or circulation decline", None, ["Print media decline structural."]),
    "UNITDSPR":   ("United Spirits", "Alcoholic Beverages", 2, 74, "Largest spirits player; premiumisation + premium segment growth.", "Premiumisation", "Tax hike or regulatory action", None, []),
    "RADICO":     ("Radico Khaitan", "Alcoholic Beverages", 2, 73, "Premium spirits + IMFL; brand ramp; export + domestic mix.", "Brand ramp", "Tax hike or competition", None, []),
    "UBL":        ("United Breweries", "Alcoholic Beverages", 2, 73, "Largest brewer; market leader; growth steady.", "Market leader + scale", "Tax hike or competition", None, []),
    "TI":         ("Tilaknagar Industries", "Alcoholic Beverages", 1, 60, "IMFL; small-cap, growth modest.", "IMFL", "Tax hike or competition", None, []),
    "ALLIEDBL":   ("Allied Blenders & Distillers", "Alcoholic Beverages", 1, 62, "IMFL; small-cap, growth steady.", "IMFL", "Tax hike or competition", None, []),
    "GLOBUSSPR":  ("Globus Spirits", "Alcoholic Beverages", 1, 60, "IMFL; small-cap, growth modest.", "IMFL", "Tax hike or competition", None, []),
    "GODFRYPHLP": ("Godfrey Phillips India", "Tobacco Products", 1, 65, "Tobacco + retail; small-cap, growth modest.", "Tobacco + retail", "Tax hike or volume weak", None, []),
    "VSTIND":     ("VST Industries", "Tobacco Products", 1, 65, "Tobacco products; small-cap, growth steady.", "Tobacco products", "Tax hike or volume weak", None, []),
    "ITC":        ("ITC", "Tobacco Products", 2, 74, "Cigarettes steady; FMCG-hotels demerger optionality.", "Cigarettes + diversification", "Cigarette tax hike", "n/a", []),
    "MANAPPURAM": ("Manappuram Finance", "Finance", 2, 76, "Gold loan + microfinance + housing; AUM growth strong; asset quality clean.", "Gold loan AUM growth", "Gold price volatility or MFI slippages", None, []),
    "MUTHOOTFIN": ("Muthoot Finance", "Finance", 2, 78, "Largest gold loan NBFC; branch expansion driving AUM growth.", "Branch + AUM growth", "Gold price volatility", None, []),
    "FORTIS":     ("Fortis Healthcare", "Healthcare", 2, 75, "Hospital chain; ARPOB growth; margin expansion underway.", "ARPOB + bed additions", "Regulatory caps pricing", None, []),
    "NH":         ("Narayana Hrudayalaya", "Healthcare", 2, 72, "Affordable hospital chain; ARPOB growth; capex done.", "ARPOB + occupancy", "Regulatory caps pricing", None, []),
    "KIMS":       ("Krishna Institute of Medical Sciences", "Healthcare", 1, 65, "Hospital chain; regional focus; small-cap, growth steady.", "Hospital chain scale", "Regulatory caps pricing", None, []),
    "SHALBY":     ("Shalby", "Healthcare", 1, 62, "Hospital chain; small-cap, growth modest.", "Hospital chain", "Regulatory caps pricing", None, []),
    "DIVISLAB":   ("Divi's Laboratories", "Pharmaceuticals", 2, 76, "API + custom synthesis; margin steady; capacity expansion.", "API + custom synthesis", "US pricing or customer concentration", None, []),
    "MANKIND":    ("Mankind Pharma", "Pharmaceuticals", 2, 75, "Domestic pharma + consumer health; chronic + acute mix; growth strong.", "Domestic + consumer health", "Regulatory action on MRP", None, []),
    "LUPIN":      ("Lupin", "Pharmaceuticals", 2, 73, "US generics + India formulations; complex generics pipeline; growth steady.", "US generics pipeline", "US FDA action", None, []),
    "TORNTPHARM": ("Torrent Pharmaceuticals", "Pharmaceuticals", 2, 73, "India + US formulations; chronic + acute mix; growth steady.", "India + US formulations", "US FDA action", None, []),
    "LAURUSLABS": ("Laurus Labs", "Pharmaceuticals", 2, 74, "API + formulations + CDMO; growth strong across segments.", "CDMO + API growth", "US pricing or customer concentration", None, []),
    "AJANTPHARM": ("Ajanta Pharma", "Pharmaceuticals", 2, 73, "India + Africa + US formulations; branded generics growth.", "Branded generics", "Regulatory action", None, []),
    "ALKEM":      ("Alkem Laboratories", "Pharmaceuticals", 2, 73, "India + US formulations; growth steady.", "India + US formulations", "US FDA action or competition", None, []),
    "IPCALAB":    ("Ipca Laboratories", "Pharmaceuticals", 2, 72, "India + US formulations; growth steady.", "India + US formulations", "US FDA action", None, []),
    "GRANULES":   ("Granules India", "Pharmaceuticals", 2, 73, "API + formulations; growth strong; market share.", "API + formulations", "US FDA action or API pricing", None, []),
    "JBCHEPHARM": ("JB Chemicals & Pharma", "Pharmaceuticals", 2, 74, "Domestic + export formulations; growth strong; chronic mix.", "Domestic + export", "US pricing or competition", None, []),
    "NATCOPHARM": ("Natco Pharma", "Pharmaceuticals", 2, 72, "Specialty + complex generics; niche growth.", "Complex generics", "US pricing or competition", None, []),
    "STRIDES":    ("Strides Pharma", "Pharmaceuticals", 1, 62, "Pharma + CDMO; small-cap, growth modest.", "Pharma + CDMO", "US FDA action", None, []),
    "ZENSARTECH": ("Zensar Technologies", "IT - Hardware", 1, 60, "Mid-cap IT; growth modest; cloud + digital services.", "Cloud + digital", "Discretionary IT spend weak", None, []),
    "CYIENT":     ("Cyient", "IT - Hardware", 1, 62, "Engineering services; aerospace + auto; small-cap, growth steady.", "Aerospace + auto", "Aerospace cycle softens", None, []),
    "HEXAWARE":   ("Hexaware Technologies", "IT - Hardware", 2, 72, "Mid-cap IT; cloud + digital services; growth steady.", "Cloud + digital", "Discretionary spend weak", None, []),
    "MASTEK":     ("Mastek", "IT - Hardware", 1, 62, "Mid-cap IT; UK + US focus; growth modest.", "UK + US IT services", "Discretionary spend weak", None, []),
    "INTELLECT":  ("Intellect Design Arena", "IT - Software", 1, 62, "Banking software; small-cap, growth modest.", "Banking software", "Banking IT spend weak", None, []),
    "STARHEALTH": ("Star Health & Allied", "Insurance", 2, 72, "Retail health insurance leader; growth strong; margin expanding.", "Health insurance scale", "Claim ratio spikes or competition", None, []),
    "ICICILOMB":  ("ICICI Lombard General", "Insurance", 2, 74, "General insurance + health; market share; growth steady.", "Market share + growth", "Claim ratio spikes or competition", None, []),
    "MAXFININCO": ("Max Financial Services", "Insurance", 2, 74, "Max Life promoter; JV with Axis; APE growth strong.", "APE growth", "Demerger execution or JV terms", None, []),
    "NIACL":      ("New India Assurance", "Insurance", 1, 65, "PSU general insurer; steady; reform-dependent.", "PSU general insurer", "Reform or claim ratio spikes", None, []),
    "GICRE":      ("General Insurance Corp", "Insurance", 1, 60, "PSU general insurer; small-cap, growth modest.", "PSU general insurer", "Claim ratio or reform", None, []),
    "GODIGIT":    ("Go Digit General Insurance", "Insurance", 1, 65, "Digital-first general insurer; growth strong; small-cap.", "Digital insurance", "Claim ratio or competition", None, []),
    "POWERGRID":  ("Power Grid Corp", "Power Infrastructure", 2, 74, "Monopoly TBCoD; capex cycle + regulated returns.", "Capex + regulated returns", "Capex delays or returns cut", None, []),
    "ADANIPOWER": ("Adani Power", "Power Generation & Distribution", 2, 73, "Capacity additions; PPA growth; balance sheet improving.", "Capacity additions", "Fuel cost spike or PPA economics", None, []),
    "JSWENERGY":  ("JSW Energy", "Power Generation & Distribution", 2, 73, "Renewable additions; thermal operations; growth strong.", "Renewable additions", "Fuel cost spike or generation cycles", None, []),
    "TORNTPOWER": ("Torrent Power", "Power Generation & Distribution", 1, 65, "Integrated power; renewables + distribution; growth steady.", "Renewables + distribution", "Regulatory issues", None, []),
    "NHPC":       ("NHPC", "Power Generation & Distribution", 2, 72, "Hydro + renewable; capex cycle; regulated returns.", "Hydro + renewable capex", "Capex delays or returns cut", None, []),
    "SJVN":       ("SJVN", "Power Generation & Distribution", 2, 72, "Hydro + solar; growth steady; capex cycle.", "Hydro + solar capex", "Capex delays", None, []),
    "IEX":        ("Indian Energy Exchange", "Power Generation & Distribution", 2, 76, "Power exchange; market leader; volume growth strong.", "Power exchange leader", "Volume weak or competition", None, []),
    "PTC":        ("PTC India", "Power Generation & Distribution", 2, 72, "Power trading; growth steady; energy transition tailwind.", "Power trading", "Volume weak", None, []),
    "HPCL":       ("Hindustan Petroleum", "Refineries", 2, 73, "Refining + marketing; petchem scale-up; margin normalization.", "Refining + petchem", "GRM compression", None, []),
    "MRPL":       ("Mangalore Refinery", "Refineries", 1, 65, "Refining; margin volatile; ONGC subsidiary.", "Refining margin", "GRM compression", None, []),
    "CHENNPETRO": ("Chennai Petroleum", "Refineries", 1, 65, "Refining; margin volatile; IOC subsidiary.", "Refining margin", "GRM compression", None, []),
    "HINDPETRO":  ("Hindustan Petroleum", "Petrochemicals", 2, 73, "Refining + petchem; growth steady; capex underway.", "Petchem + refining", "GRM compression or petchem oversupply", None, []),
    "DCMSHRIRAM": ("DCM Shriram", "Petrochemicals", 2, 73, "Chlor-vinyl + sugar + fertilisers; growth strong; capex done.", "Chlor-vinyl scale-up", "Commodity volatility or competition", None, []),
    "TCI":        ("Transport Corp of India", "Logistics", 2, 70, "Surface transport; supply chain; growth steady.", "Surface transport", "Freight rates weak", None, []),
    "BLUEDART":   ("Blue Dart Express", "Logistics", 1, 65, "Express logistics; SME + B2B; growth modest.", "Express logistics", "E-commerce parcel volume weak", None, []),
    "GESHIP":     ("Great Eastern Shipping", "Shipping", 2, 71, "Tanker + dry bulk shipping; freight cycle recovery.", "Freight cycle", "Freight rates weak", None, []),
    "SCI":        ("Shipping Corporation", "Shipping", 1, 65, "PSU shipping; tanker + bulk; rate sensitive.", "Tanker + bulk", "Freight rates weak", None, []),
    "CONCOR":     ("Container Corp of India", "Logistics", 2, 72, "Rail container logistics; market leader; growth steady.", "Container rail logistics", "EXIM volumes weak or competition", None, []),
    "MAHLOG":     ("Mahindra Logistics", "Logistics", 1, 65, "3PL + supply chain; growth steady; small-cap.", "3PL + supply chain", "Auto volumes weak", None, []),
    "JSWINFRA":   ("JSW Infrastructure", "Marine Port & Services", 2, 73, "Port + container terminal; capacity expansion; growth strong.", "Port + capacity expansion", "Cargo volumes weak", None, []),
    "GPPL":       ("Gujarat Pipavav Port", "Marine Port & Services", 2, 70, "Port + container terminal; growth steady.", "Port operations", "Cargo volumes weak", None, []),
    "SAIL":       ("Steel Authority of India", "Steel", 2, 73, "PSU steel; capacity utilisation rising; valuation attractive.", "Capacity utilisation", "Steel prices correct sharply", None, []),
    "JSPL":       ("Jindal Steel & Power", "Steel", 2, 75, "India utilisation rising; export markets steady.", "Utilisation + exports", "Steel prices correct", None, []),
    "APLAPOLLO":  ("APL Apollo Tubes", "Steel", 2, 76, "Largest structural steel pipe maker; capacity expansion; growth strong.", "Capacity + market share", "Steel prices correct", None, []),
    "JINDALSAW":  ("Jindal Saw", "Steel", 2, 72, "Steel pipes + iron ore mining; integrated; growth steady.", "Pipes + iron ore mix", "Steel prices correct", None, []),
    "WELCORP":    ("Welspun Corp", "Steel", 2, 72, "Steel pipes + iron ore mining; integrated; growth steady.", "Pipes + iron ore mix", "Steel prices correct", None, []),
    "FINCABLES":  ("Finolex Cables", "Cables", 2, 73, "Cables + electrical products; growth steady; rural distribution strong.", "Cables + distribution", "Commodity volatility or demand slow", None, []),
    "VGUARD":     ("V-Guard Industries", "Consumer Durables", 2, 72, "Stabilizers + switches + fans; south India focus; growth steady.", "South India franchise", "Commodity volatility or demand slow", None, []),
    "CROMPTON":   ("Crompton Greaves Consumer", "Consumer Durables", 2, 74, "Fans + appliances; growth strong; market share gains.", "Fans + market share", "Demand softens or competition", None, []),
    "BAJAJELEC":  ("Bajaj Electricals", "Consumer Durables", 1, 62, "Appliances + EPC; small-cap, growth modest.", "Appliances + EPC", "Demand softens", None, []),
    "TTKPT":      ("TTK Prestige", "Consumer Durables", 1, 60, "Kitchen + home appliances; small-cap, growth modest.", "Kitchen appliances", "Demand softens or competition", None, []),
    "WHIRLPOOL":  ("Whirlpool of India", "Consumer Durables", 1, 62, "Home appliances; market share gains; small-cap, growth modest.", "Home appliances", "Demand softens or competition", None, []),
    "KAJARIACER": ("Kajaria Ceramics", "Ceramic Products", 2, 75, "Largest tiles player; growth strong; capacity expansion.", "Tiles + capacity expansion", "Real estate demand softens or input cost", None, []),
    "CERA":       ("Cera Sanitaryware", "Sanitaryware", 2, 72, "Sanitaryware; growth steady; market share gains.", "Sanitaryware", "Real estate demand softens", None, []),
    "HINDWARE":   ("Hindware Home Innovation", "Sanitaryware", 1, 60, "Sanitaryware + faucets; small-cap, growth modest.", "Sanitaryware + faucets", "Real estate demand softens", None, []),
    "KANSAINER":  ("Kansai Nerolac Paints", "Paints/Varnish", 2, 73, "Auto + industrial paints; growth steady; brand investment.", "Auto + industrial paints", "Auto cycle weak or input cost spike", None, []),
    "INDIGOPNTS": ("Indigo Paints", "Paints/Varnish", 2, 70, "Mid-tier decorative paints; regional expansion; growth steady.", "Regional expansion", "Competition or input cost spike", None, []),
    "ASAHIINDIA": ("Asahi India Glass", "Glass & Glass Products", 2, 74, "Auto glass; market leader; growth strong.", "Auto glass leader", "Auto cycle weak or input cost", None, []),
    "SAINTGOBAIN":("Saint-Gobain Sekurit", "Glass & Glass Products", 2, 72, "Auto + architectural glass; growth steady.", "Glass mix", "Auto cycle weak", None, []),
    "TIMKEN":     ("Timken India", "Bearings", 2, 75, "Bearings + linear motion; industrial growth; market share gains.", "Bearings + linear motion", "Industrial growth slow", None, []),
    "SKFINDIA":   ("SKF India", "Bearings", 2, 73, "Bearings + seals; industrial + auto; growth steady.", "Bearings + seals", "Auto or industrial cycle weak", None, []),
    "SCHAEFFLER": ("Schaeffler India", "Bearings", 2, 75, "Bearings + auto + industrial; growth strong.", "Bearings + auto + industrial", "Auto or industrial cycle weak", None, []),
    "BHARATFORG": ("Bharat Forge", "Castings, Forgings & Fastners", 2, 76, "Largest forging player; defence + auto + industrial; growth strong.", "Defence + auto + industrial", "Auto cycle weak or defence delays", None, []),
    "SONACOMS":   ("Sona Comstar", "Auto Ancillaries", 2, 75, "Auto precision components; EV + ICE mix; growth strong.", "Auto + EV mix", "Auto cycle weak or EV ramp stalls", None, []),
    "ENDURANCE":  ("Endurance Technologies", "Auto Ancillaries", 2, 73, "Auto components + aluminium die-casting; growth steady.", "Auto components", "Auto cycle weak", None, []),
    "UNOMINDA":   ("Uno Minda", "Auto Ancillaries", 2, 76, "Auto components + switches + sensors; growth strong.", "Auto components + EV", "Auto cycle weak or input cost spike", None, []),
    "MOTHERSON":  ("Samvardhana Motherson", "Auto Ancillaries", 2, 74, "Auto components wiring harness; growth steady; global mix.", "Wiring harness + global mix", "Auto cycle weak or margin pressure", None, []),
    "EXIDEIND":   ("Exide Industries", "Auto Ancillaries", 2, 72, "Lead-acid batteries + lithium; growth steady; capex underway.", "Battery + lithium expansion", "Auto cycle weak or competition", None, []),
    "AMARAJABAT": ("Amara Raja Energy & Mobility", "Auto Ancillaries", 2, 70, "Batteries + lithium; growth strong; capex underway.", "Battery + lithium", "Capex delays or competition", None, []),
    "BOSCHLTD":   ("Bosch", "Auto Ancillaries", 2, 75, "Auto components + technology; growth strong; market leader.", "Auto components + tech", "Auto cycle weak", None, []),
    "CGPOWER":    ("CG Power & Industrial Solutions", "Capital Goods - Electrical Equipment", 2, 75, "Transformers + T&D; order book strong; growth steady.", "T&D order book", "Order inflows weak or commodity spike", None, []),
    "BHARATBIJLEE":("Bharat Bijlee", "Capital Goods - Electrical Equipment", 1, 65, "Transformers; small-cap, order book modest.", "Transformers", "Order inflows weak", None, []),
    "SCHNEIDER":  ("Schneider Electric Infrastructure", "Capital Goods - Electrical Equipment", 2, 75, "T&D + automation; market leader; growth strong.", "T&D + automation", "Capex cycle weak", None, []),
    "KEC":        ("KEC International", "Capital Goods-Non Electrical Equipment", 2, 73, "Power T&D + cables; order book strong; execution steady.", "Order book strong", "Order inflows weak or commodity spike", None, []),
    "HGINFRA":    ("H.G. Infra Engineering", "Construction", 2, 73, "Road + highway construction; order book strong; execution healthy.", "Order book + execution", "Order inflows weak", None, []),
    "IRB":        ("IRB Infrastructure", "Construction", 1, 65, "Toll roads + construction; order book modest; cash flow watch.", "Toll road assets", "Toll traffic weak or refinancing", None, []),
    "PNCINFRA":   ("PNC Infratech", "Construction", 2, 72, "EPC + HAM + toll; order book strong; execution healthy.", "Order book + HAM", "Order inflows weak or execution", None, []),
    "EVERESTIND": ("Everest Industries", "Cement - Products", 1, 60, "Building products + asbestos; small-cap, growth modest.", "Building products", "Real estate demand weak", None, ["Asbestos legacy; small-cap."]),
    "NIITLTD":    ("NIIT", "Computer Education", 1, 60, "IT training + education services; small-cap, growth modest.", "IT training", "IT training demand softens", None, []),
    "CLSEL":      ("CL Educate", "Computer Education", 1, 58, "Test prep + vocational; small-cap, demand cyclical.", "Vocational training", "Test prep cycle softens", None, ["Small-cap."]),
    "APTECHT":    ("Aptech", "Computer Education", 1, 55, "IT training + vocational; small-cap, growth modest.", "IT training", "IT training demand softens", None, []),
    "ICRA":       ("ICRA", "Credit Rating Agencies", 1, 65, "Credit rating; small-cap, growth modest, duopoly.", "Rating scale", "Issuance activity weak", None, []),
    "CRISIL":     ("CRISIL", "Credit Rating Agencies", 2, 75, "Credit rating + research; market leader; growth steady.", "Rating + research", "Issuance activity weak", None, []),
    "KALYANKJIL": ("Kalyan Jewellers India", "Diamond, Gems and Jewellery", 2, 75, "Jewellery chain; store expansion; growth strong.", "Store expansion + market share", "Gold price weak or demand softens", None, []),
    "PCJEWELLER": ("PC Jeweller", "Diamond, Gems and Jewellery", 1, 50, "Jewellery + gold loans; small-cap, balance sheet stretched.", "Jewellery + gold loan", "Gold price weak or recovery stalls", None, ["Balance sheet stretched."]),
    "PATANJALI":  ("Patanjali Foods", "Edible Oil", 2, 73, "Edible oil + FMCG; distribution strong; growth steady.", "Edible oil + FMCG", "Commodity volatility or competition", None, []),
    "GOLDBEES":   ("Nippon India ETF Gold BeES", "ETF", 2, 70, "Gold ETF; passive; growth tracks gold price.", "Gold exposure", "Gold price weak", None, []),
    "NIFTYBEES":  ("Nippon India ETF Nifty 50 BeES", "ETF", 2, 70, "Nifty 50 ETF; passive; growth tracks index.", "Index exposure", "Index weak", None, []),
    "MAITHANALL": ("Maithan Alloys", "Ferro Alloys", 2, 73, "Ferro alloys + manganese; growth strong; exports scaling.", "Ferro alloys + exports", "Steel cycle weak or commodity volatility", None, []),
    "CHAMBLFERT": ("Chambal Fertilizers", "Fertilizers", 2, 73, "Urea + DAP manufacturing; growth steady; capacity expansion.", "Urea + DAP capacity", "Subsidy delays or volume weak", None, []),
    "COROMANDEL": ("Coromandel International", "Fertilizers", 2, 75, "Fertilizers + crop protection; market leader; growth strong.", "Crop protection + fertilizers", "Subsidy delays or volume weak", None, []),
    "GSFC":       ("Gujarat State Fertilizers", "Fertilizers", 1, 60, "PSU fertilizer; small-cap, growth modest.", "Fertilizer demand", "Subsidy delays or volume weak", None, []),
    "RCF":        ("Rashtriya Chemicals & Fertilisers", "Fertilizers", 1, 60, "PSU fertilizer; small-cap, growth modest.", "Fertilizer demand", "Subsidy delays or volume weak", None, []),
    "NFL":        ("National Fertilizers", "Fertilizers", 1, 60, "PSU fertilizer; small-cap, growth modest.", "Fertilizer demand", "Subsidy delays or volume weak", None, []),
    "ZUARI":      ("Zuari Agro Chemicals", "Fertilizers", 1, 55, "Fertilizer + sugar; small-cap, growth modest.", "Fertilizer + sugar", "Subsidy delays or volume weak", None, []),
    "DHANUKA":    ("Dhanuka Agritech", "Agro Chemicals", 2, 73, "Agrochemicals + crop protection; domestic + exports; growth steady.", "Crop protection + exports", "Agchem cycle weak", None, []),
    "RALLIS":     ("Rallis India", "Agro Chemicals", 1, 65, "Tata group agrochemical; domestic + exports; growth modest.", "Crop protection", "Agchem cycle weak", None, []),
    "BAYERCROP":  ("Bayer CropScience", "Agro Chemicals", 2, 75, "Crop protection + seeds; market leader; growth strong.", "Crop protection + seeds", "Agchem cycle weak", None, []),
    "POONAWALLA": ("Poonawalla Financing", "Finance", 2, 75, "NBFC; growth strong; promoter strength; AUM scale-up.", "AUM growth", "Asset quality slips", None, []),
    "FIVE":       ("Five-Star Business Finance", "Finance", 2, 75, "MSME + small business lending; growth strong; asset quality clean.", "MSME lending", "MSME cycle weakens", None, []),
    "LICHSGFIN":  ("LIC Housing Finance", "Finance", 2, 76, "Housing finance; growth steady; market share strong.", "Housing finance scale", "Housing demand stalls", None, []),
    "PNBHOUSING": ("PNB Housing Finance", "Finance", 2, 73, "Housing finance; growth strong; asset quality clean.", "Housing finance growth", "Housing demand stalls or asset quality", None, []),
    "CANFINHOME": ("Can Fin Homes", "Finance", 2, 72, "Housing finance; growth steady; niche focus.", "Housing finance", "Housing demand stalls", None, []),
    "AADHARHFC":  ("Aadhar Housing Finance", "Finance", 2, 73, "Affordable housing; growth strong; asset quality clean.", "Affordable housing", "Housing demand stalls", None, []),
    "AAVAS":      ("Aavas Financiers", "Finance", 2, 73, "Affordable housing; growth strong; asset quality clean.", "Affordable housing", "Housing demand stalls", None, []),
    "HOMEFIRST":  ("Home First Finance", "Finance", 2, 73, "Affordable housing; growth strong; asset quality clean.", "Affordable housing", "Housing demand stalls", None, []),
    "IIFL":       ("IIFL Finance", "Finance", 2, 75, "NBFC; gold loan + microfinance + housing; AUM growth strong.", "NBFC AUM growth", "Asset quality or growth weak", None, []),
    "MAS":        ("MAS Financial Services", "Finance", 1, 60, "MSME + housing finance; small-cap, growth modest.", "MSME + housing", "Asset quality or growth weak", None, []),
    "HDFCAMC":    ("HDFC Asset Management", "Financial Services", 2, 76, "Largest AMC; SIP growth strong; market share.", "AMC market leader", "Equity market weak or SIPs slow", None, []),
    "NAM-INDIA":  ("Nippon Life India AMC", "Financial Services", 2, 76, "Fast-growing AMC; market share gains; SIP momentum.", "Market share gains", "Equity market weak or SIPs slow", None, []),
    "ICICIAMC":   ("ICICI Pru AMC", "Financial Services", 2, 75, "AMC; market share strong; SIP growth.", "AMC scale", "Equity market weak", None, []),
    "UTIAMC":     ("UTI AMC", "Financial Services", 1, 65, "AMC; small-cap, growth modest, market share under pressure.", "AMC scale", "Equity market weak", None, []),
    "NSDL":       ("National Securities Depository", "Financial Services", 2, 75, "Demat depository; near-monopoly with CDSL; growth strong.", "Demat depository", "Demat growth stalls", None, []),
    "MOTILALOFS": ("Motilal Oswal Financial", "Stock/Commodity Brokers", 2, 76, "Broking + distribution; cash segment growth; AUM scaling.", "Broking + AUM", "Broking volumes weak", None, []),
    "ANGELONE":   ("Angel One", "Stock/Commodity Brokers", 2, 76, "Discount broking; market share gains; growth strong.", "Market share", "Broking volumes weak", None, []),
    "IIFLSEC":    ("IIFL Securities", "Stock/Commodity Brokers", 1, 65, "Broking + distribution; growth steady.", "Broking + distribution", "Broking volumes weak", None, []),
    "5PAISA":     ("5paisa Capital", "Stock/Commodity Brokers", 1, 55, "Discount broking; small-cap, growth modest.", "Discount broking", "Broking volumes weak", None, []),
    "PRUDENT":    ("Prudent Corporate Advisory", "Stock/Commodity Brokers", 2, 76, "Distributor + broking; market share gains; growth strong.", "Distributor + broking", "Broking volumes weak", None, []),
    "SHAREINDIA": ("Share India Securities", "Stock/Commodity Brokers", 2, 75, "Discount broking; growth strong; market share gains.", "Discount broking", "Broking volumes weak", None, []),
    "EDELWEISS":  ("Edelweiss Financial Services", "Financial Services", 1, 55, "Diversified financial services; small-cap, growth weak.", "Diversified financial", "Asset quality or growth weak", None, []),
    "MMTC":       ("MMTC", "Trading", 1, 60, "PSU trading; commodities; small-cap, growth modest.", "Commodity trading", "Commodity volumes weak", None, []),
    "STC":        ("State Trading Corp", "Trading", 1, 60, "PSU trading; small-cap, growth modest.", "Commodity trading", "Commodity volumes weak", None, []),
    "BATAINDIA":  ("Bata India", "Leather", 2, 73, "Footwear retail; brand strength; growth steady; distribution expansion.", "Brand + distribution", "Footwear demand softens", None, []),
    "RELAXO":     ("Relaxo Footwears", "Leather", 2, 73, "Footwear; brand ramp; growth steady.", "Brand + distribution", "Footwear demand softens", None, []),
    "INDIAMART":  ("IndiaMart InterMESH", "Online Media", 2, 75, "B2B marketplace; growth strong; market leader.", "B2B marketplace", "B2B demand weak or competition", None, []),
    "CARTRADE":   ("CarTrade Tech", "Online Media", 1, 62, "Auto classifieds; small-cap, growth modest.", "Auto classifieds", "Auto demand weak", None, []),
    "JUSTDIAL":   ("Just Dial", "Online Media", 1, 55, "Search + listings; small-cap, growth modest.", "Search + listings", "Search disruption or competition", None, []),
    "INFOEDGE":   ("Info Edge (Naukri)", "Online Media", 2, 76, "Naukri + 99acres + Jeevansathi; hiring recovery underway.", "Recruitment recovery", "Hiring market stalls", None, []),
    "JKPAPER":    ("JK Paper", "Paper", 2, 73, "Packaging + writing paper; growth steady; capacity expansion.", "Paper + packaging", "Paper demand softens or input cost", None, []),
    "CENTURYPPR": ("Century Pulp & Paper", "Paper", 1, 55, "Pulp + paper; small-cap, growth modest.", "Pulp + paper", "Paper demand softens", None, []),
    "UFLEX":      ("Uflex", "Packaging", 2, 75, "Flexible packaging + films; growth strong; capex done.", "Flexible packaging", "Polymer cost spike or demand softens", None, []),
    "JINDALPOLY": ("Jindal Poly Films", "Packaging", 2, 72, "Polyester + BOPET films; growth steady.", "Polyester films", "Polymer cost spike", None, []),
    "COSMOFILMS": ("Cosmo Films", "Packaging", 2, 73, "BOPP films; growth strong; global mix.", "BOPP films", "Polymer cost spike or competition", None, []),
    "EPL":        ("EPL (formerly Essel Propack)", "Packaging", 2, 73, "Tubes + packaging; global mix; growth steady.", "Tubes + global mix", "Polymer cost or competition", None, []),
    "MANJUSHREE": ("Manjushree Technopack", "Packaging", 2, 74, "PET preforms + bottles; growth strong; capex done.", "PET + bottles", "Polymer cost spike", None, []),
    "POLYPLEX":   ("Polyplex Corporation", "Packaging", 1, 60, "BOPET films; small-cap, growth modest.", "BOPET films", "Polymer cost spike", None, []),
    "FINPIPE":    ("Finolex Industries", "Plastic products", 2, 73, "PVC pipes + fittings; agricultural + plumbing; growth steady.", "PVC + plumbing", "PVC cost spike or demand softens", None, []),
    "SUPREMEIND": ("Supreme Industries", "Plastic products", 2, 75, "PVC + piping + packaging; market leader; growth strong.", "PVC + packaging", "PVC cost spike or demand softens", None, []),
    "PRINCEPIPE": ("Prince Pipes & Fittings", "Plastic products", 2, 72, "PVC + CPVC pipes; growth steady; distribution expansion.", "PVC + distribution", "PVC cost spike or demand softens", None, []),
    "GREENLAM":   ("Greenlam Industries", "Plywood Boards/Laminates", 2, 75, "Laminates + veneers; market leader; growth strong.", "Laminates scale", "Real estate demand softens", None, []),
    "CENTURYPLY": ("Century Plyboards", "Plywood Boards/Laminates", 2, 74, "Plywood + laminates; growth strong; distribution expansion.", "Plywood + distribution", "Real estate demand softens", None, []),
    "FLAIR":      ("Flair Writing Industries", "Printing & Stationery", 1, 65, "Writing instruments; small-cap, growth steady.", "Writing instruments", "Demand softens or competition", None, []),
    "RAJESHEXPO": ("Rajesh Exports", "Diamond, Gems and Jewellery", 1, 55, "Gold refining + jewellery; small-cap, margin pressure.", "Gold + refining", "Gold price weak or margin pressure", None, []),
    "MAZDOCK":    ("Mazagon Dock Shipbuilders", "Ship Building", 2, 73, "Submarine + destroyer order book; P-75I pipeline; strong execution track record.", "Submarine order book", "Order inflows slip or execution delays", "n/a", []),
    "COCHINSHIP": ("Cochin Shipyard", "Ship Building", 2, 72, "Navy + commercial shipbuilding; aircraft carrier MRO scale-up; defence export visibility.", "Navy order book", "Defence order cycle slows or commercial shipbuilding margins compress", "n/a", []),
    "GRSE":       ("Garden Reach Shipbuilders", "Ship Building", 2, 73, "Navy + commercial shipbuilding; order book strong; growth steady.", "Navy order book", "Order inflows weak", "n/a", []),
    "INDUSTOWER": ("Indus Towers", "Telecomm-Service", 2, 73, "Tower infra; market leader; growth steady.", "Tower infra", "Telecom capex weak or tenancy losses", None, []),
    "BHARTIHEX":  ("Bharti Hexacom", "Telecomm-Service", 2, 75, "Telecom operator (Rajasthan circle); growth strong; ARPU.", "Telecom operator", "Tariff hike flow slow", None, []),
    "TATACOMM":   ("Tata Communications", "Telecomm-Service", 1, 62, "Enterprise + wholesale; small-cap, growth modest.", "Enterprise + wholesale", "Competition or price pressure", None, []),
    "MTNL":       ("Mahanagar Telephone Nigam", "Telecomm-Service", 1, 50, "PSU telecom; small-cap, growth weak, structural issues.", "PSU telecom", "Structural issues or competition", None, ["Structural issues."]),
    "HFCL":       ("HFCL", "Telecomm Equipment & Infra Services", 2, 72, "Telecom equipment + cables; growth steady; order book.", "Telecom equipment + cables", "Telecom capex weak", None, []),
    "STERLITE":   ("Sterlite Technologies", "Telecomm Equipment & Infra Services", 2, 75, "Optical fibre + cables; market leader; growth strong.", "Optical fibre + cables", "Telecom capex weak", None, []),
    "TEJASNET":   ("Tejas Networks", "Telecomm Equipment & Infra Services", 2, 72, "Telecom equipment; growth steady; order book strong.", "Telecom equipment", "Telecom capex weak or competition", None, []),
    "ITI":        ("ITI", "Telecomm Equipment & Infra Services", 1, 55, "PSU telecom equipment; small-cap, growth weak.", "PSU telecom", "Order inflows weak", None, []),
    "MICROMAX":   ("Micromax Informatics", "Telecom-Handsets/Mobile", 1, 50, "Mobile handsets; small-cap, competition intense.", "Mobile handsets", "Competition or demand weak", None, ["Intense competition."]),
    "EMBASSY":    ("Embassy Office Parks REIT", "Real Estate Investment Trusts", 2, 74, "Largest office REIT; rentals steady; growth stable.", "Office REIT", "Office demand weak", None, []),
    "MINDSPACE":  ("Mindspace Business Parks REIT", "Real Estate Investment Trusts", 2, 73, "Office REIT; rentals steady; growth stable.", "Office REIT", "Office demand weak", None, []),
    "BROOKFIELD": ("Brookfield India REIT", "Real Estate Investment Trusts", 2, 72, "Office REIT; rentals steady; growth stable.", "Office REIT", "Office demand weak", None, []),
    "NXST":       ("Nexus Select Trust REIT", "Real Estate Investment Trusts", 2, 73, "Retail mall REIT; rentals steady; growth stable.", "Retail mall REIT", "Retail demand weak", None, []),
    "IRBINVIT":   ("IRB InvIT Fund", "Infrastructure Investment Trusts", 1, 60, "Toll road InvIT; small-cap, growth modest.", "Toll road InvIT", "Toll traffic weak", None, []),
    "OIL":        ("Oil India", "Crude Oil & Natural Gas", 2, 73, "Crude oil + gas; growth steady; dividend play.", "Crude oil + gas", "Crude price correction", None, []),
    "NMDC":       ("NMDC", "Mining & Mineral products", 2, 74, "Iron ore mining; pricing tailwind; dividend play.", "Iron ore pricing", "Iron ore prices correct", None, []),
    "HINDZINC":   ("Hindustan Zinc", "Non Ferrous Metals", 2, 75, "Zinc + lead mining; pricing tailwind; cash flow strong.", "Zinc pricing", "Zinc prices correct", None, []),
    "SANDHAR":    ("Sandhar Technologies", "Castings, Forgings & Fastners", 1, 60, "Auto components; small-cap, growth modest.", "Auto components", "Auto cycle weak", None, []),
    "MINDACORP":  ("Mindacorp", "Castings, Forgings & Fastners", 1, 60, "Auto components; small-cap, growth modest.", "Auto components", "Auto cycle weak", None, []),
    "ALOKINDS":   ("Alok Industries", "Castings, Forgings & Fastners", 1, 50, "Textile + polyester; small-cap, growth weak.", "Textile + polyester", "Demand weak or competition", None, ["Weak fundamentals."]),
    "BIRLATYRES": ("Birla Tyres", "Tyres", 1, 60, "Tyres; small-cap, growth modest.", "Tyres", "Auto cycle weak or competition", None, []),
    "NRBBEARING": ("NRB Bearings", "Bearings", 1, 60, "Bearings; small-cap, growth modest.", "Bearings", "Auto cycle weak", None, []),
    "CARBORUNIV": ("Carborundum Universal", "Engineering", 2, 74, "Abrasives + ceramics + refractories; growth strong.", "Abrasives + industrial", "Industrial cycle weak", None, []),
    "GRINDWELL":  ("Grindwell Norton", "Engineering", 2, 74, "Abrasives + ceramics; growth strong; market share.", "Abrasives + ceramics", "Industrial cycle weak", None, []),
    "HONEYWELL":  ("Honeywell Automation", "Engineering", 2, 75, "Industrial automation; growth strong; market leader.", "Industrial automation", "Capex cycle weak", None, []),
    "CCL":        ("CCL Products (India)", "Plantation & Plantation Products", 2, 73, "Tea + coffee + instant beverages; growth strong; distribution expansion.", "Tea + coffee + beverages", "Commodity cost spike", None, []),
    "MCLEODRUSS": ("McLeod Russel", "Plantation & Plantation Products", 1, 55, "Tea company; debt + cost issues; small-cap.", "Tea", "Commodity cost or financial issues", None, ["Debt + cost issues."]),
    "EVEREADY":   ("Eveready Industries", "Dry cells", 1, 60, "Batteries + lighting; small-cap, growth modest.", "Batteries + lighting", "Battery demand softens", None, []),
    "NMDC":       ("NMDC", "Mining & Mineral products", 2, 74, "Iron ore mining; pricing tailwind; dividend play.", "Iron ore pricing", "Iron ore prices correct", None, []),
    "SAIL":       ("Steel Authority of India", "Steel", 2, 73, "PSU steel; capacity utilisation rising; valuation attractive.", "Capacity utilisation", "Steel prices correct sharply", None, []),
    "JSPL":       ("Jindal Steel & Power", "Steel", 2, 75, "India utilisation rising; export markets steady.", "Utilisation + exports", "Steel prices correct", None, []),
    "EMBASSY":    ("Embassy Office Parks REIT", "Real Estate Investment Trusts", 2, 74, "Largest office REIT; rentals steady; growth stable.", "Office REIT", "Office demand weak", None, []),
    "NXST":       ("Nexus Select Trust REIT", "Real Estate Investment Trusts", 2, 73, "Retail mall REIT; rentals steady; growth stable.", "Retail mall REIT", "Retail demand weak", None, []),
    "IFGLREFRAC": ("IFGL Refractories", "Refractories", 1, 60, "Refractories; small-cap, growth modest.", "Refractories", "Steel cycle weak", None, []),
    "VESUVIUS":   ("Vesuvius India", "Refractories", 1, 65, "Refractories; small-cap, growth modest.", "Refractories", "Steel cycle weak", None, []),
    "BALAJITELE": ("Balaji Telefilms", "Entertainment", 1, 55, "TV content production; small-cap, growth weak.", "TV content", "Content demand weak", None, []),
    "QUESS":      ("Quess Corp", "Staffing and Outsourcing", 1, 62, "Staffing + facility management; small-cap, growth modest.", "Staffing + facility", "Hiring market weak", None, []),
    "TEAMLEASE":  ("TeamLease Services", "Staffing and Outsourcing", 2, 75, "Staffing + payroll; growth strong; market leader.", "Staffing + payroll", "Hiring market weak", None, []),
    "FIRST":      ("FirstMeridian", "Staffing and Outsourcing", 1, 60, "Staffing; small-cap, growth modest.", "Staffing", "Hiring market weak", None, []),
}

SECTOR_MAP = {
    'Aerospace & Defence': 'Capital Goods & Engineering',
    'Agro Chemicals': 'Chemicals',
    'Air Transport Service': 'Travel & Tourism',
    'Alcoholic Beverages': 'FMCG',
    'Auto Ancillaries': 'Auto Components',
    'Automobile': 'Auto Components',
    'Banks': 'Banking & Financials',
    'Bearings': 'Auto Components',
    'Cables': 'Capital Goods & Engineering',
    'Capital Goods - Electrical Equipment': 'Capital Goods & Engineering',
    'Capital Goods-Non Electrical Equipment': 'Capital Goods & Engineering',
    'Castings, Forgings & Fastners': 'Capital Goods & Engineering',
    'Cement': 'Cement',
    'Cement - Products': 'Cement',
    'Ceramic Products': 'Consumer Durables',
    'Chemicals': 'Chemicals',
    'Computer Education': 'Education',
    'Construction': 'Capital Goods & Engineering',
    'Consumer Durables': 'Consumer Durables',
    'Credit Rating Agencies': 'Capital Markets',
    'Crude Oil & Natural Gas': 'Oil & Gas',
    'Diamond, Gems and Jewellery': 'Consumer Durables',
    'Diversified': 'FMCG',
    'Dry cells': 'Consumer Durables',
    'E-Commerce/App based Aggregator': 'Consumer Internet',
    'Edible Oil': 'FMCG',
    'Education': 'Consumer Internet',
    'Electronics': 'Electronics / EMS',
    'Engineering': 'Capital Goods & Engineering',
    'Entertainment': 'Media - Print/Television/Radio',
    'ETF': 'Capital Markets',
    'Ferro Alloys': 'Metals & Mining',
    'Fertilizers': 'Chemicals',
    'Finance': 'Banking & Financials',
    'Financial Services': 'Banking & Financials',
    'FMCG': 'FMCG',
    'Gas Distribution': 'Oil & Gas',
    'Glass & Glass Products': 'Consumer Durables',
    'Healthcare': 'Healthcare Services',
    'Hotels & Restaurants': 'Travel & Tourism',
    'Infrastructure Developers & Operators': 'Realty',
    'Infrastructure Investment Trusts': 'Real Estate Investment Trusts',
    'Insurance': 'Insurance',
    'IT - Hardware': 'IT Services',
    'IT - Software': 'IT Services',
    'Leather': 'Consumer Durables',
    'Logistics': 'Logistics',
    'Marine Port & Services': 'Logistics',
    'Media - Print/Television/Radio': 'Consumer Internet',
    'Mining & Mineral products': 'Metals & Mining',
    'Miscellaneous': 'Financial Services',
    'Non Ferrous Metals': 'Metals & Mining',
    'Oil Drill/Allied': 'Oil & Gas',
    'Online Media': 'Consumer Internet',
    'Packaging': 'Capital Goods & Engineering',
    'Paints/Varnish': 'Consumer Durables',
    'Paper': 'Materials',
    'Petrochemicals': 'Oil & Gas',
    'Pharmaceuticals': 'Pharmaceuticals',
    'Plantation & Plantation Products': 'FMCG',
    'Plastic products': 'Capital Goods & Engineering',
    'Plywood Boards/Laminates': 'Consumer Durables',
    'Power Generation & Distribution': 'Power',
    'Power Infrastructure': 'Power',
    'Printing & Stationery': 'FMCG',
    'Quick Service Restaurant': 'Consumer Internet',
    'Railways': 'Capital Goods & Engineering',
    'Readymade Garments/ Apparells': 'Consumer Durables',
    'Real Estate Investment Trusts': 'Real Estate Investment Trusts',
    'Realty': 'Realty',
    'Refineries': 'Oil & Gas',
    'Refractories': 'Capital Goods & Engineering',
    'Retail': 'Retail',
    'Sanitaryware': 'Consumer Durables',
    'Ship Building': 'Capital Goods & Engineering',
    'Shipping': 'Logistics',
    'Steel': 'Metals & Mining',
    'Stock/Commodity Brokers': 'Capital Markets',
    'Sugar': 'FMCG',
    'Telecom-Handsets/Mobile': 'Telecom',
    'Telecomm Equipment & Infra Services': 'Telecom',
    'Telecomm-Service': 'Telecom',
    'Textiles': 'Consumer Durables',
    'Tobacco Products': 'FMCG',
    'Trading': 'Trading',
    'Tyres': 'Auto Components',
}

rows = json.loads(PATH.read_text(encoding="utf-8"))
existing_syms = set(r['symbol'] for r in rows)
new_rows = []
for sym, (name, subindustry, stage, score, trigger, ev, inv, cap, redFlags) in NEW.items():
    if sym in existing_syms:
        continue
    sector = SECTOR_MAP.get(subindustry, 'Financial Services')
    new_rows.append({
        'symbol': sym,
        'yf': f'{sym}.NS',
        'name': name,
        'sector': sector,
        'subIndustry': subindustry,
        'stage': stage,
        'score': score,
        'trigger': trigger,
        'evidence': [ev],
        'invalidation': inv,
        'capacity': cap,
        'redFlags': redFlags,
    })

merged = rows + new_rows
PATH.write_text(json.dumps(merged, indent=2, ensure_ascii=False), encoding='utf-8')
print(f'Before: {len(rows)} | New: {len(new_rows)} | Total: {len(merged)}')
print(f'Sub-industries covered: {len(set(r.get("subIndustry","") for r in merged))}')
